#!/usr/bin/python

from fevertools import defaults

from jinja2 import Environment, FileSystemLoader
import os

group_vars = None
if len(os.sys.argv) == 4 and os.sys.argv[2] == '--vars' :
    group_vars = os.sys.argv.pop()
    os.sys.argv.pop()

if len(os.sys.argv) != 2 :
    print "Usage: %s role_directory [--vars filename]\n" % os.sys.argv[0]
    os.sys.exit(1)


env = Environment(loader=FileSystemLoader(os.sys.argv[1]))
template = env.get_template('templates/local_settings.j2')

runtime = {
  'appname' : 'fever2',
  'username' : 'fever'
  }


defaults = defaults( env , runtime , group_vars )

for line in template.render(defaults).splitlines() :
    print line

